# Generated by Django 3.0.7 on 2020-06-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvgVolume',
            fields=[
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('day_avg_30', models.FloatField(blank=True, default=None, null=True)),
                ('day_avg_60', models.FloatField(blank=True, default=None, null=True)),
                ('day_avg_150', models.FloatField(blank=True, default=None, null=True)),
                ('total_avg', models.FloatField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'AvgVolume',
            },
        ),
        migrations.CreateModel(
            name='Earnings',
            fields=[
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('zac_score', models.IntegerField(blank=True, default=None, null=True)),
                ('zac_score_value', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('upcoming_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('upcoming_time', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Earnings',
            },
        ),
        migrations.CreateModel(
            name='Growth',
            fields=[
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('y_2015', models.FloatField(blank=True, default=None, null=True)),
                ('y_2016', models.FloatField(blank=True, default=None, null=True)),
                ('y_2017', models.FloatField(blank=True, default=None, null=True)),
                ('y_2018', models.FloatField(blank=True, default=None, null=True)),
                ('y_2019', models.FloatField(blank=True, default=None, null=True)),
                ('y_2020', models.FloatField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'Growth',
            },
        ),
        migrations.CreateModel(
            name='Tickers',
            fields=[
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Tickers',
            },
        ),
        migrations.CreateModel(
            name='VolumePoints',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=10)),
                ('date', models.DateTimeField()),
                ('volume', models.FloatField()),
            ],
            options={
                'db_table': 'VolumePoints',
            },
        ),
        migrations.CreateModel(
            name='ClosingPoints',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=10)),
                ('date', models.DateTimeField()),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'ClosingPoints',
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]
