# Generated by Django 3.0.7 on 2020-06-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0002_statistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyZScore',
            fields=[
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('z_score', models.FloatField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'DailyZScore',
            },
        ),
        migrations.AddField(
            model_name='tickers',
            name='supported',
            field=models.BooleanField(default=True),
        ),
    ]
